# Generated by Django 4.1.5 on 2023-01-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_applied_at_candidatesapplied_appliedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Permenet', 'Permeanet'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Permenet', max_length=10),
        ),
    ]
